import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { Waves } from "../../components/svg-components/Waves";
import ThemeToggle from "@/components/ThemeToggle";
import LanguageToggle from "@/components/LanguageToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-200 dark:bg-gray-800`}>
        <ChakraProvider>
          <Waves />
          <ThemeToggle />
          <LanguageToggle />
          <div className="flex min-h-screen flex-col items-center justify-center py-24 px-1">
            {children}
          </div>
        </ChakraProvider>
      </body>
    </html>
  );
}
